name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Feature'
    labels:
      - 'feature'
      - 'enhancement'
      - 'breaking'
  - title: 'Bug Fix'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Maintenance Update'
    labels:
      - 'chore'
      - 'maintenance'
  - title: 'Dependency Upgrade'
    labels:
      - 'chore'
      - 'maintenance'
exclude-labels:
  - skip-changelog
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'enhancement'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'maintenance'
      - 'dependency'
      - 'bug'
  default: patch
template: |
  ## Changes

  $CHANGES
